version: '3.3'
services:
  db:
    build:
      context: ./src/db
  
  api:
    build: 
      context: ./src/api
    ports:
      - "3000:3000"
    volumes:
      - ./src/api/:/code
    depends_on:
      - "db"
  
  web:
    build:
      context: ./src/web
    ports:
      - "9000:9000"
    depends_on:
      - "api"